<?php
/** Atelier — recherche : résultats publics contextualisés, sans interface JavaScript obligatoire. */
defined( 'ABSPATH' ) || exit;
get_header();
$query = get_search_query();
?>
<main class="atelier-search" id="main-content" data-content-kind="search-results">
	<header class="atelier-search__hero"><p class="atelier-kicker">Recherche dans les archives</p><h1>Retrouver un contexte, une décision ou une réponse.</h1><form role="search" method="get" action="<?php echo esc_url( home_url( '/' ) ); ?>"><label class="screen-reader-text" for="atelier-search-field">Rechercher</label><input id="atelier-search-field" type="search" name="s" value="<?php echo esc_attr( $query ); ?>" placeholder="Ex. documenter une décision" /><button type="submit">Rechercher</button></form></header>
	<div class="atelier-search__layout"><section aria-labelledby="atelier-search-results-title"><header class="atelier-section-heading"><p>Sources correspondantes</p><h2 id="atelier-search-results-title"><?php echo $query ? esc_html( sprintf( 'Résultats pour « %s »', $query ) ) : 'Commencez une recherche'; ?></h2></header><?php if ( have_posts() ) : while ( have_posts() ) : the_post(); $type = get_post_type(); $kind = function_exists( 'bbp_get_reply_post_type' ) && $type === bbp_get_reply_post_type() ? 'Réponse' : ( function_exists( 'bbp_get_topic_post_type' ) && $type === bbp_get_topic_post_type() ? 'Discussion' : 'Archive' ); ?><article class="atelier-search-result"><p class="atelier-contribution__kind"><?php echo esc_html( $kind ); ?> · <time datetime="<?php echo esc_attr( get_post_time( DATE_W3C, true ) ); ?>"><?php echo esc_html( get_the_date( 'd.m.Y' ) ); ?></time></p><h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3><p><?php echo esc_html( wp_trim_words( wp_strip_all_tags( get_the_excerpt() ?: get_the_content() ), 38 ) ); ?></p><footer><span><?php echo esc_html( get_the_author() ); ?></span><span><?php echo esc_html( atelier_total_upvotes( get_the_ID() ) ); ?> votes utiles</span><a href="<?php the_permalink(); ?>">Ouvrir la source</a></footer></article><?php endwhile; the_posts_pagination( array( 'screen_reader_text' => 'Navigation des résultats' ) ); else : ?><p class="atelier-empty">Aucune source ne correspond à cette formulation. Essayez un terme plus précis ou consultez les espaces du forum.</p><?php endif; ?></section><aside class="atelier-search__aside"><p class="atelier-kicker">Repères</p><p>La recherche privilégie les discussions et réponses publiées. Chaque résultat renvoie vers sa source canonique.</p><a class="atelier-text-link" href="<?php echo esc_url( atelier_home_section_url( 'espaces' ) ); ?>">Parcourir les espaces</a></aside></div>
</main>
<?php get_footer(); ?>
