<?php
defined( 'ABSPATH' ) || exit;

final class PFC_Admin {
	public static function init(): void {
		add_action( 'admin_menu', array( __CLASS__, 'menu' ) );
		add_action( 'admin_enqueue_scripts', array( __CLASS__, 'assets' ) );
	}
	public static function menu(): void { add_menu_page( 'Premium Forum Core', 'Premium Forum', 'manage_options', 'pfc-import', array( __CLASS__, 'page' ), 'dashicons-format-chat', 58 ); }
	public static function assets( string $hook ): void { if ( 'toplevel_page_pfc-import' !== $hook ) return; wp_enqueue_style( 'pfc-admin', PFC_URL . 'assets/admin.css', array(), PFC_VERSION ); }
	public static function page(): void {
		if ( ! current_user_can( 'manage_options' ) ) return;
		$job_id = absint( $_GET['job'] ?? 0 );
		$notice = sanitize_text_field( wp_unslash( $_GET['pfc_notice'] ?? '' ) );
		$job            = $job_id ? PFC_Importer::get_job( $job_id ) : null;
			$errors         = $job_id ? PFC_Importer::get_items( $job_id, array( 'error' ) ) : array();
			$created_items  = $job_id ? PFC_Importer::get_items( $job_id, array( 'created' ) ) : array();
		$job_summary    = $job && ! empty( $job->summary ) ? json_decode( $job->summary, true ) : array();
		$summary_errors = is_array( $job_summary['errors'] ?? null ) ? $job_summary['errors'] : array();
		$diagnostic     = PFC_Importer::schema_diagnostics( $job_id );
		?>
		<div class="wrap pfc-admin"><h1>Importer l’historique sans perdre sa mémoire</h1><p class="description">Téléversez un pack CSV, validez son mapping, lancez un dry run puis exécutez l’import. Chaque objet créé est journalisé pour un rollback ciblé.</p>
		<?php if ( $notice ) : ?><div class="notice notice-<?php echo esc_attr( 'error' === ( $_GET['pfc_kind'] ?? '' ) ? 'error' : 'success' ); ?>"><p><?php echo esc_html( $notice ); ?></p></div><?php endif; ?>
		<section class="pfc-card"><h2>Diagnostic du journal</h2><p><code><?php echo esc_html( $diagnostic['jobs_table'] ); ?></code> : <?php echo $diagnostic['tables']['jobs'] ? 'présente' : 'absente'; ?> · <code><?php echo esc_html( $diagnostic['items_table'] ); ?></code> : <?php echo $diagnostic['tables']['items'] ? 'présente' : 'absente'; ?></p><?php if ( $diagnostic['last_error'] ) : ?><p class="description"><strong>Dernière erreur SQL :</strong> <?php echo esc_html( $diagnostic['last_error'] ); ?></p><?php endif; ?><?php if ( $diagnostic['actions'] ) : ?><p class="description">Journal du job : <?php foreach ( $diagnostic['actions'] as $action ) { echo esc_html( $action['action_name'] . ' = ' . $action['total'] . ' ' ); } ?></p><?php endif; ?></section><section class="pfc-card"><h2>1. Sources CSV</h2><form method="post" enctype="multipart/form-data" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><?php wp_nonce_field( 'pfc_upload_pack' ); ?><input type="hidden" name="action" value="pfc_upload_pack"><input type="file" name="pfc_files[]" multiple accept=".csv,.zip,text/csv,application/zip" required><button class="button button-primary">Téléverser le pack</button></form><p class="description">Téléversez les quatre CSV séparément ou un ZIP contenant uniquement <code>users.csv</code>, <code>forums.csv</code>, <code>topics.csv</code> et <code>replies.csv</code>.</p><p><?php foreach ( array_keys( PFC_Importer::schemas() ) as $type ) : ?><a class="button-link" href="<?php echo esc_url( wp_nonce_url( admin_url( 'admin-post.php?action=pfc_download_template&type=' . $type ), 'pfc_template' ) ); ?>">Télécharger <?php echo esc_html( $type ); ?>-template.csv</a> <?php endforeach; ?></p></section>
			<?php if ( $job_id ) : ?><section class="pfc-card"><h2>2. Validation et dry run</h2><p><strong>Job #<?php echo esc_html( $job_id ); ?></strong> · Statut : <code><?php echo esc_html( $job ? $job->status : 'inconnu' ); ?></code></p><?php if ( $created_items ) : ?><p><strong><?php echo esc_html( count( $created_items ) ); ?></strong> objet(s) créés et journalisés pour rollback.</p><?php endif; ?><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><?php wp_nonce_field( 'pfc_dry_run' ); ?><input type="hidden" name="action" value="pfc_dry_run"><input type="hidden" name="job_id" value="<?php echo esc_attr( $job_id ); ?>"><button class="button">Lancer le dry run</button></form><?php if ( $summary_errors || $errors ) : ?><h3>Erreurs détectées</h3><table class="widefat striped"><thead><tr><th>Fichier / ligne</th><th>Erreur</th></tr></thead><tbody><?php foreach ( $summary_errors as $error ) : ?><tr><td><?php echo esc_html( ( $error['file'] ?? 'fichier' ) . ' · ligne ' . ( $error['row'] ?? 0 ) ); ?></td><td><?php echo esc_html( $error['message'] ?? 'Erreur non précisée' ); ?></td></tr><?php endforeach; ?><?php foreach ( $errors as $error ) : $detail = json_decode( $error->details, true ); ?><tr><td><?php echo esc_html( $error->object_type . ' · ligne ' . $error->source_row ); ?></td><td><?php echo esc_html( $detail['message'] ?? 'Erreur non précisée' ); ?></td></tr><?php endforeach; ?></tbody></table><?php endif; ?></section><section class="pfc-card"><h2>3. Exécuter ou annuler</h2><p>La création est bloquée tant que le job n’est pas <code>validated</code>. Le rollback cible exclusivement les objets journalisés comme créés par ce job.</p><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="pfc-inline"><?php wp_nonce_field( 'pfc_execute_import' ); ?><input type="hidden" name="action" value="pfc_execute_import"><input type="hidden" name="job_id" value="<?php echo esc_attr( $job_id ); ?>"><button class="button button-primary">Exécuter l’import validé</button></form><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="pfc-inline"><?php wp_nonce_field( 'pfc_rollback_import' ); ?><input type="hidden" name="action" value="pfc_rollback_import"><input type="hidden" name="job_id" value="<?php echo esc_attr( $job_id ); ?>"><button class="button-link-delete">Rollback de ce job</button></form></section><?php endif; ?>
		</div><?php
	}
}
