from pathlib import Path
import re

path = Path('/home/ubuntu/atelier-wordpress/atelier/bbpress/content-single-topic.php')
text = path.read_text()

new_actions = '''<div class="atelier-thread__actions" role="group" aria-label="Actions de la discussion"><a class="atelier-button atelier-button--reply" href="#new-reply"><svg aria-hidden="true" viewBox="0 0 24 24" focusable="false"><path d="M5 5.5h14a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-8l-4.5 3v-3H5a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2Z" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"/></svg><span>Répondre</span></a><?php if ( class_exists( 'PFC_Community' ) ) : $following = is_user_logged_in() && PFC_Community::is_following( get_current_user_id(), $topic_id ); ?><button type="button" class="atelier-button atelier-button--follow" data-pfc-follow data-topic-id="<?php echo esc_attr( $topic_id ); ?>" data-login="<?php echo esc_url( wp_login_url( $topic_url ) ); ?>" aria-pressed="<?php echo $following ? 'true' : 'false'; ?>"><svg aria-hidden="true" viewBox="0 0 24 24" focusable="false"><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9ZM10 21h4" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg><span data-follow-label><?php echo $following ? 'Vous suivez' : 'Suivre'; ?></span></button><?php endif; ?><button type="button" class="atelier-button atelier-button--share" data-atelier-share data-url="<?php echo esc_url( $topic_url ); ?>" data-label="Partager"><svg aria-hidden="true" viewBox="0 0 24 24" focusable="false"><circle cx="18" cy="5" r="2.2" fill="none" stroke="currentColor" stroke-width="1.7"/><circle cx="6" cy="12" r="2.2" fill="none" stroke="currentColor" stroke-width="1.7"/><circle cx="18" cy="19" r="2.2" fill="none" stroke="currentColor" stroke-width="1.7"/><path d="m8 11 7.8-4.5M8 13l7.8 4.5" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg><span data-share-label>Partager</span></button><button type="button" class="atelier-button atelier-button--save" data-atelier-save data-save-key="atelier-topic-<?php echo esc_attr( $topic_id ); ?>" aria-pressed="false"><svg aria-hidden="true" viewBox="0 0 24 24" focusable="false"><path d="M6 4.5h12v15l-6-3.8-6 3.8v-15Z" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"/></svg><span data-save-label>Enregistrer</span></button></div>'''
text, count = re.subn(r'<div class="atelier-thread__actions".*?</div>', new_actions, text, count=1, flags=re.S)
assert count == 1, 'actions block not found'

new_footer = '''<footer class="atelier-post-footer"><span class="atelier-topic-upvotes" aria-label="Votes utiles du sujet"><svg aria-hidden="true" viewBox="0 0 24 24" focusable="false"><path d="M7 10v10H4V10h3Zm3 10h6.5a2 2 0 0 0 1.94-1.52l1.35-5.4A2 2 0 0 0 17.85 10H14l.6-3.1A2.4 2.4 0 0 0 12.25 4L10 10v10Z" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"/></svg><strong><?php echo esc_html( $vote_count ); ?></strong> upvotes</span><span class="atelier-source-note"><svg aria-hidden="true" viewBox="0 0 24 24" focusable="false"><path d="M6 3.5h9l3 3V20.5H6zM15 3.5v4h4M9 12h6M9 15h6" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/></svg><span>Source stable</span><button type="button" data-atelier-share data-url="<?php echo esc_url( $topic_url ); ?>" data-label="<?php echo esc_attr( wp_parse_url( $topic_url, PHP_URL_PATH ) ?: 'Copier le lien' ); ?>"><span data-share-label><?php echo esc_html( wp_parse_url( $topic_url, PHP_URL_PATH ) ?: 'Copier le lien' ); ?></span></button></span></footer>'''
old_footer = '<footer class="atelier-post-footer"><span>Message initial</span><a href="#reponses">Consulter les réponses</a></footer>'
assert old_footer in text, 'initial footer not found'
text = text.replace(old_footer, new_footer, 1)

new_reading = '''<section class="atelier-reading-card" id="machine-reading"><header><span>✧ Lecture claire</span><small>LLM-FIRST</small></header><h2>Ce sujet expose ce qui compte.</h2><p>Ce panneau explique comment le sujet est découpé pour une lecture humaine et pour les moteurs de recherche : source canonique, message initial, auteurs, dates et réponses restent séparables.</p><dl><div><dt>Source</dt><dd>Canonique</dd></div><div><dt>Structure</dt><dd>HTML initial</dd></div><div><dt>Dates</dt><dd>Historiques</dd></div></dl><button type="button" class="atelier-signal-copy" data-atelier-share data-url="<?php echo esc_url( $topic_url ); ?>" data-label="Copier le lien source"><svg aria-hidden="true" viewBox="0 0 24 24" focusable="false"><rect x="8" y="8" width="11" height="11" rx="1" fill="none" stroke="currentColor" stroke-width="1.6"/><path d="M5 16V5.5A1.5 1.5 0 0 1 6.5 4H17" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/></svg><span data-share-label>Copier le lien source</span></button></section>'''
text, count = re.subn(r'<section class="atelier-reading-card".*?</section>', new_reading, text, count=1, flags=re.S)
assert count == 1, 'reading card not found'

new_related = '''<section class="atelier-related"><p class="atelier-kicker">À poursuivre</p><ol><?php foreach ( $related as $related_topic ) : $related_replies = function_exists( 'bbp_get_topic_reply_count' ) ? (int) bbp_get_topic_reply_count( $related_topic->ID ) : 0; ?><li><a href="<?php echo esc_url( get_permalink( $related_topic ) ); ?>"><span class="atelier-related__number"><?php echo esc_html( str_pad( (string) ( $related_topic->ID % 100 ), 2, '0', STR_PAD_LEFT ) ); ?></span><span class="atelier-related__copy"><strong><?php echo esc_html( get_the_title( $related_topic ) ); ?></strong><small><svg aria-hidden="true" viewBox="0 0 24 24" focusable="false"><path d="M5 6.5h14v10H9l-4 3v-3H5z" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/></svg><?php echo esc_html( $related_replies ); ?> réponse<?php echo 1 === $related_replies ? '' : 's'; ?></small></span><span class="atelier-related__arrow" aria-hidden="true">›</span></a></li><?php endforeach; ?></ol></section>'''
text, count = re.subn(r'<section class="atelier-related".*?</section>', new_related, text, count=1, flags=re.S)
assert count == 1, 'related section not found'

old_collection = '<a class="atelier-collection-card" href="<?php echo esc_url( function_exists( \'atelier_methods_url\' ) ? atelier_methods_url() : home_url( \'/methodes/\' ) ); ?>"><span>Collection</span><strong>Écrire pour être relu</strong><small>Explorer les repères →</small></a>'
new_collection = '<a class="atelier-collection-card" href="<?php echo esc_url( function_exists( \'atelier_methods_url\' ) ? atelier_methods_url() : home_url( \'/methodes/\' ) ); ?>" aria-label="Explorer la collection Écrire pour être relu"><span>Collection</span><strong>Écrire pour être relu</strong><small>Explorer les repères <span aria-hidden="true">↗</span></small></a>'
assert old_collection in text, 'collection card not found'
text = text.replace(old_collection, new_collection, 1)

old_h1 = '</h1>\n\t\t\t\t<div class="atelier-thread__facts">'
new_h1 = '</h1><p class="atelier-thread__deck">Nous cherchons une méthode simple pour que les conversations restent claires, citables et utiles — pour les membres comme pour les systèmes qui les découvrent.</p>\n\t\t\t\t<div class="atelier-thread__facts">'
assert old_h1 in text, 'title insertion point not found'
text = text.replace(old_h1, new_h1, 1)

path.write_text(text)
print('updated', path)
