<?php
/**
 * Atelier — discussion éditoriale tactile : rail d’index, source canonique,
 * lecture claire et réponses séparées pour les humains et les systèmes d’extraction.
 */
defined( 'ABSPATH' ) || exit;
$topic_id    = bbp_get_topic_id();
$author_id   = bbp_get_topic_author_id( $topic_id );
$forum_id    = bbp_get_topic_forum_id( $topic_id );
$reply_count = (int) bbp_get_topic_reply_count( $topic_id );
$vote_count  = (int) atelier_total_upvotes( $topic_id );
$asset_base  = trailingslashit( get_template_directory_uri() ) . 'assets/images/';
$topic_url   = get_permalink( $topic_id );
$forum_title = bbp_get_forum_title( $forum_id );
$related     = get_posts( array( 'post_type' => bbp_get_topic_post_type(), 'post_status' => 'publish', 'posts_per_page' => 3, 'post__not_in' => array( $topic_id ), 'orderby' => 'date', 'order' => 'DESC', 'no_found_rows' => true ) );
?>
<main id="main-content" class="atelier-thread" data-content-kind="discussion-forum-posting">
	<section id="topic-root" class="atelier-thread__hero" aria-label="Présentation du forum"><div><p class="atelier-kicker"><span aria-hidden="true"></span>Mémoire collective · 2024</p><h2>Les bonnes conversations ne doivent pas disparaître.</h2><p>Atelier transforme les discussions exigeantes en ressources vivantes, sourcées et partageables.</p><a href="#topic-root">Lire la discussion du jour <span class="atelier-glyph atelier-glyph--arrow" aria-hidden="true"></span></a></div><figure><img src="<?php echo esc_url( $asset_base . 'atelier-hero.webp' ); ?>" alt="Composition éditoriale abstraite de papier ivoire, d’ombres bleutées et d’un ruban vermillon." fetchpriority="high"></figure></section>
	<div class="atelier-thread__layout">
		<aside class="atelier-thread__rail" aria-label="Index de la discussion">
			<p class="atelier-thread__rail-label">Index / 05</p>
			<nav>
				<a href="#topic-root"><span>01</span>Contexte</a>
				<a href="#message-initial"><span>02</span>Message initial</a>
				<a href="#reponses"><span>03</span>Réponses</a>
				<a href="#machine-reading"><span>04</span>Lecture machine</a>
			</nav>
			<div class="atelier-thread__rail-filter">
				<p>Explorer par</p>
<a href="#reponses" data-atelier-filter="all" aria-current="true">Tout voir</a>
					<a href="#reponses" data-atelier-filter="featured">Contributions repérées</a>
					<a href="#reponses" data-atelier-filter="latest">Dernières réponses</a>
			</div>
		</aside>

		<div class="atelier-thread__main">
			<header class="atelier-thread__intro">
				<p class="atelier-kicker">Atelier · discussion archivée</p>
				<nav class="atelier-breadcrumb" aria-label="Fil d’Ariane"><?php bbp_breadcrumb(); ?></nav>
				<div class="atelier-thread__source-line"><span>SOURCE <strong><?php echo esc_html( str_pad( (string) $topic_id, 4, '0', STR_PAD_LEFT ) ); ?></strong></span><i></i><span><?php echo esc_html( $forum_title ); ?></span></div>
				<h1 dir="<?php echo esc_attr( atelier_content_dir( (string) get_the_title( $topic_id ) ) ); ?>"><?php bbp_topic_title( $topic_id ); ?></h1><p class="atelier-thread__deck">Nous cherchons une méthode simple pour que les conversations restent claires, citables et utiles — pour les membres comme pour les systèmes qui les découvrent.</p>
				<div class="atelier-thread__facts"><span><?php echo esc_html( $reply_count ); ?> réponse<?php echo 1 === $reply_count ? '' : 's'; ?></span><span><?php echo esc_html( $vote_count ); ?> votes utiles</span><time datetime="<?php echo esc_attr( get_post_time( DATE_W3C, true, $topic_id ) ); ?>">Publié <?php echo esc_html( get_the_date( 'd.m.Y', $topic_id ) ); ?></time></div>
				<div class="atelier-thread__actions" role="group" aria-label="Actions de la discussion"><a class="atelier-button atelier-button--reply" href="#new-reply"><svg aria-hidden="true" viewBox="0 0 24 24" focusable="false"><path d="M5 5.5h14a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-8l-4.5 3v-3H5a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2Z" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"/></svg><span>Répondre</span></a><?php if ( class_exists( 'PFC_Community' ) ) : $following = is_user_logged_in() && PFC_Community::is_following( get_current_user_id(), $topic_id ); ?><button type="button" class="atelier-button atelier-button--follow" data-pfc-follow data-topic-id="<?php echo esc_attr( $topic_id ); ?>" data-login="<?php echo esc_url( wp_login_url( $topic_url ) ); ?>" aria-pressed="<?php echo $following ? 'true' : 'false'; ?>"><svg aria-hidden="true" viewBox="0 0 24 24" focusable="false"><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9ZM10 21h4" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg><span data-follow-label><?php echo $following ? 'Vous suivez' : 'Suivre'; ?></span></button><?php endif; ?><button type="button" class="atelier-button atelier-button--share" data-atelier-share data-url="<?php echo esc_url( $topic_url ); ?>" data-label="Partager"><svg aria-hidden="true" viewBox="0 0 24 24" focusable="false"><circle cx="18" cy="5" r="2.2" fill="none" stroke="currentColor" stroke-width="1.7"/><circle cx="6" cy="12" r="2.2" fill="none" stroke="currentColor" stroke-width="1.7"/><circle cx="18" cy="19" r="2.2" fill="none" stroke="currentColor" stroke-width="1.7"/><path d="m8 11 7.8-4.5M8 13l7.8 4.5" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg><span data-share-label>Partager</span></button><button type="button" class="atelier-button atelier-button--save" data-atelier-save data-save-key="atelier-topic-<?php echo esc_attr( $topic_id ); ?>" aria-pressed="false"><svg aria-hidden="true" viewBox="0 0 24 24" focusable="false"><path d="M6 4.5h12v15l-6-3.8-6 3.8v-15Z" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"/></svg><span data-save-label>Enregistrer</span></button></div>
			</header>

			<article id="message-initial" class="atelier-initial-post" data-topic-id="<?php bbp_topic_id(); ?>">
				<aside class="atelier-author-card"><span class="atelier-avatar atelier-avatar--large" style="background:<?php echo esc_attr( atelier_avatar_color( $author_id ) ); ?>"><?php echo esc_html( atelier_initials( $author_id ) ); ?></span><span class="atelier-author-card__role">Question posée par</span></aside>
				<div class="atelier-initial-post__body"><p class="atelier-initial-post__label">Message initial</p><div class="atelier-initial-post__identity"><header class="atelier-post-meta"><span class="atelier-author"><?php bbp_topic_author_link( array( 'type' => 'name' ) ); ?></span><span class="atelier-rank"><?php echo esc_html( atelier_rank( $author_id ) ); ?></span><?php if ( function_exists( 'atelier_user_role_label' ) ) : ?><span class="atelier-role-badge"><?php echo esc_html( atelier_user_role_label( $author_id ) ); ?></span><?php endif; ?></header><time datetime="<?php echo esc_attr( get_post_time( DATE_W3C, true, $topic_id ) ); ?>"><?php echo esc_html( get_the_date( 'd F Y', $topic_id ) ); ?></time></div><div class="atelier-initial-post__content" dir="<?php echo esc_attr( atelier_content_dir( (string) get_post_field( 'post_content', $topic_id ) ) ); ?>"><?php bbp_topic_content( $topic_id ); ?></div><footer class="atelier-post-footer"><span class="atelier-topic-upvotes"><svg aria-hidden="true" viewBox="0 0 24 24" focusable="false"><path d="M7 10v10H4V10h3Zm3 10h6.5a2 2 0 0 0 1.94-1.52l1.35-5.4A2 2 0 0 0 17.85 10H14l.6-3.1A2.4 2.4 0 0 0 12.25 4L10 10v10Z" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"/></svg><strong><?php echo esc_html( $vote_count ); ?></strong> upvotes</span><span class="atelier-source-note"><svg aria-hidden="true" viewBox="0 0 24 24" focusable="false"><path d="M6 3.5h9l3 3V20.5H6zM15 3.5v4h4M9 12h6M9 15h6" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/></svg><span>Source stable</span><button type="button" data-atelier-share data-url="<?php echo esc_url( $topic_url ); ?>" data-label="<?php echo esc_attr( wp_parse_url( $topic_url, PHP_URL_PATH ) ?: 'Copier le lien' ); ?>"><span data-share-label><?php echo esc_html( wp_parse_url( $topic_url, PHP_URL_PATH ) ?: 'Copier le lien' ); ?></span></button></span></footer></div>
			</article>

			<section id="reponses" class="atelier-replies" data-replies-section aria-labelledby="atelier-replies-title"><header class="atelier-section-heading"><p>La conversation continue</p><h2 id="atelier-replies-title"><?php echo esc_html( $reply_count ); ?> réponse<?php echo 1 === $reply_count ? '' : 's'; ?> qui font avancer le sujet</h2><label class="atelier-replies__sort">Trier <select aria-label="Trier les réponses" data-atelier-sort><option value="relevance">Par pertinence</option><option value="date">Par date</option><option value="votes">Par upvotes</option></select></label></header><?php if ( bbp_has_replies() ) : while ( bbp_replies() ) : bbp_the_reply(); if ( (int) bbp_get_reply_id() !== (int) $topic_id ) bbp_get_template_part( 'loop', 'single-reply' ); endwhile; else : ?><p class="atelier-empty">Aucune réponse documentée pour le moment.</p><?php endif; ?></section>
			<section id="new-reply" class="atelier-reply-composer" aria-labelledby="atelier-reply-title"><header class="atelier-section-heading"><p>Votre contribution</p><h2 id="atelier-reply-title">Ajoutez une réponse qui fait avancer le sujet.</h2></header><?php if ( is_user_logged_in() && function_exists( 'bbp_get_template_part' ) ) : ?><p class="atelier-reply-composer__hint">Votre nom, votre rang et la date de publication seront associés clairement à votre contribution.</p><?php bbp_get_template_part( 'form', 'reply' ); else : ?><p>Connectez-vous pour répondre à cette discussion.</p><a class="atelier-button atelier-button--primary" href="<?php echo esc_url( wp_login_url( $topic_url . '#new-reply' ) ); ?>">Se connecter</a><?php endif; ?></section>
		</div>

		<aside class="atelier-thread__aside" aria-label="Lecture claire et ressources liées">
			<section class="atelier-reading-card" id="machine-reading"><header><span>✧ Lecture claire</span><small>LLM-FIRST</small></header><h2>Ce sujet expose ce qui compte.</h2><p>Ce panneau explique comment le sujet est découpé pour une lecture humaine et pour les moteurs de recherche : source canonique, message initial, auteurs, dates et réponses restent séparables.</p><dl><div><dt>Source</dt><dd>Canonique</dd></div><div><dt>Structure</dt><dd>HTML initial</dd></div><div><dt>Dates</dt><dd>Historiques</dd></div></dl><button type="button" class="atelier-signal-copy" data-atelier-share data-url="<?php echo esc_url( $topic_url ); ?>" data-label="Copier le lien source"><svg aria-hidden="true" viewBox="0 0 24 24" focusable="false"><rect x="8" y="8" width="11" height="11" rx="1" fill="none" stroke="currentColor" stroke-width="1.6"/><path d="M5 16V5.5A1.5 1.5 0 0 1 6.5 4H17" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/></svg><span data-share-label>Copier le lien source</span></button></section>
			<section class="atelier-thread__stats" aria-label="Repères du sujet"><div><span><?php echo esc_html( $reply_count ); ?></span><small>réponses</small></div><div><span><?php echo esc_html( $vote_count ); ?></span><small>upvotes</small></div><div><span><?php echo esc_html( human_time_diff( get_post_time( 'U', true, $topic_id ), current_time( 'timestamp' ) ) ); ?></span><small>d’activité</small></div></section>
			<figure class="atelier-thread__figure"><img src="<?php echo esc_url( $asset_base . 'atelier-knowledge-map.webp' ); ?>" alt="Carte abstraite en papiers superposés, traversée par un marqueur vermillon." loading="lazy"><figcaption>Une discussion lisible garde chaque source à sa place.</figcaption></figure>
			<section class="atelier-related"><p class="atelier-kicker">À poursuivre</p><ol><?php foreach ( $related as $related_topic ) : $related_replies = function_exists( 'bbp_get_topic_reply_count' ) ? (int) bbp_get_topic_reply_count( $related_topic->ID ) : 0; ?><li><a href="<?php echo esc_url( get_permalink( $related_topic ) ); ?>"><span class="atelier-related__number"><?php echo esc_html( str_pad( (string) ( $related_topic->ID % 100 ), 2, '0', STR_PAD_LEFT ) ); ?></span><span class="atelier-related__copy"><strong><?php echo esc_html( get_the_title( $related_topic ) ); ?></strong><small><svg aria-hidden="true" viewBox="0 0 24 24" focusable="false"><path d="M5 6.5h14v10H9l-4 3v-3H5z" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/></svg><?php echo esc_html( $related_replies ); ?> réponse<?php echo 1 === $related_replies ? '' : 's'; ?></small></span><span class="atelier-related__arrow" aria-hidden="true">›</span></a></li><?php endforeach; ?></ol></section>
	            <a class="atelier-collection-card" href="<?php echo esc_url( function_exists( 'atelier_methods_url' ) ? atelier_methods_url() : home_url( '/methodes/' ) ); ?>" aria-label="Collection Écrire pour être relu Explorer les repères"><span>Collection </span><strong>Écrire pour être relu </strong><small>Explorer les repères <span aria-hidden="true">↗</span></small></a>
		</aside>
	</div>
</main>
