<?php
/** Atelier — profil bbPress : identité persistante et chronologie compacte des publications publiques. */
defined( 'ABSPATH' ) || exit;
$user_id = bbp_get_displayed_user_id();
$user = get_userdata( $user_id );
$post_types = array_filter( array( function_exists( 'bbp_get_topic_post_type' ) ? bbp_get_topic_post_type() : 'topic', function_exists( 'bbp_get_reply_post_type' ) ? bbp_get_reply_post_type() : 'reply' ) );
$contributions = get_posts( array( 'post_type' => $post_types, 'post_status' => 'publish', 'author' => $user_id, 'posts_per_page' => 20, 'orderby' => 'date', 'order' => 'DESC', 'no_found_rows' => true ) );
?>
<main class="atelier-profile" id="main-content" data-content-kind="member-profile">
	<a class="atelier-backlink" href="<?php echo esc_url( function_exists( 'atelier_discussions_url' ) ? atelier_discussions_url() : atelier_home_section_url( 'sources-recentes' ) ); ?>">Retour aux discussions</a>
	<header class="atelier-profile__hero">
		<div class="atelier-profile__identity"><span class="atelier-avatar atelier-avatar--profile" style="background:<?php echo esc_attr( atelier_avatar_color( $user_id ) ); ?>" aria-hidden="true"><?php echo esc_html( atelier_initials( $user_id ) ); ?></span><div><p class="atelier-kicker">Archive membre · @<?php echo esc_html( $user ? $user->user_nicename : '' ); ?></p><h1><?php echo esc_html( $user ? $user->display_name : 'Membre' ); ?></h1><p class="atelier-profile__role"><?php echo esc_html( atelier_rank( $user_id ) ?: 'Membre' ); ?></p></div></div>
		<?php if ( $user && $user->description ) : ?><p class="atelier-profile__bio"><?php echo esc_html( $user->description ); ?></p><?php endif; ?>
	</header>
	<div class="atelier-profile__layout"><section class="atelier-profile__stream" aria-labelledby="atelier-contributions-title"><header class="atelier-section-heading"><p>Trace publique</p><h2 id="atelier-contributions-title">Contributions documentées</h2></header><?php if ( $contributions ) : foreach ( $contributions as $contribution ) : $is_reply = function_exists( 'bbp_get_reply_post_type' ) && $contribution->post_type === bbp_get_reply_post_type(); $url = $is_reply && function_exists( 'bbp_get_reply_url' ) ? bbp_get_reply_url( $contribution->ID ) : get_permalink( $contribution ); ?><article class="atelier-contribution" data-contribution-kind="<?php echo esc_attr( $is_reply ? 'reply' : 'topic' ); ?>"><p class="atelier-contribution__kind"><?php echo esc_html( $is_reply ? 'Réponse' : 'Discussion' ); ?> · <time datetime="<?php echo esc_attr( get_post_time( DATE_W3C, true, $contribution ) ); ?>"><?php echo esc_html( get_the_date( 'd.m.Y', $contribution ) ); ?></time></p><h3><a href="<?php echo esc_url( $url ); ?>"><?php echo esc_html( get_the_title( $contribution ) ?: 'Réponse archivée' ); ?></a></h3><p><?php echo esc_html( wp_trim_words( wp_strip_all_tags( $contribution->post_content ), 36 ) ); ?></p><footer><span><?php echo esc_html( atelier_total_upvotes( $contribution->ID ) ); ?> votes utiles</span><a href="<?php echo esc_url( $url ); ?>">Lire la source</a></footer></article><?php endforeach; else : ?><p class="atelier-empty">Aucune contribution publique n’est encore archivée pour ce membre.</p><?php endif; ?></section><aside class="atelier-profile__aside" aria-label="Repères du membre"><p class="atelier-kicker">Identité</p><dl><div><dt>Rang</dt><dd><?php echo esc_html( atelier_rank( $user_id ) ?: 'Membre' ); ?></dd></div><div><dt>Sujets</dt><dd><?php echo esc_html( atelier_user_topic_total( $user_id ) ); ?></dd></div><div><dt>Réponses</dt><dd><?php echo esc_html( atelier_user_reply_total( $user_id ) ); ?></dd></div></dl></aside></div>
</main>
